---
- name: CIS 1.1.1 Configure Filesystem Kernel Modules

  hosts: all

  become: yes

  gather_facts: no


  tasks:

    - name: Show Ansible role path
      command: ansible-config dump --only-changed
      register: ansible_config_output

    - debug:
        var: ansible_config_output.stdout_lines


  roles:

    - cis_1_1_1_filesystem_kernel_modules
