---
- name: Display EC2 Host Information
  hosts: all
  become: yes

  tasks:

    - name: Gather OS facts
      ansible.builtin.setup:
        gather_subset:
          - min

    - name: Display EC2 hostname and OS
      ansible.builtin.debug:
        msg:
          Hostname: "{{ ansible_hostname }}"
          OS: "{{ ansible_distribution }}"
          Version: "{{ ansible_distribution_version }}"
          Kernel: "{{ ansible_kernel }}"
