---

cis_filesystem_modules:

  - cramfs
  - freevxfs
  - hfs
  - hfsplus
  - jffs2


cis_disable_unused_filesystems: false


cis_modprobe_directory: /etc/modprobe.d

cis_disable_command: /bin/false