---

- name: Initialize failed module list
  set_fact:

    cis_failed_modules: []


- name: Check filesystem module existence

  shell: |

    find /lib/modules/$(uname -r)/kernel/fs \
    -type d \
    -name "{{ item }}"

  register: module_exists

  failed_when: false

  changed_when: false

  loop: "{{ cis_filesystem_modules }}"



- name: Check loaded filesystem modules

  shell: |

    lsmod | grep -w "{{ item }}"

  register: module_loaded

  failed_when: false

  changed_when: false

  loop: "{{ cis_filesystem_modules }}"



- name: Check modprobe configuration

  shell: |

    modprobe --showconfig | grep -E "^(install|blacklist).*{{ item }}"

  register: module_config

  failed_when: false

  changed_when: false

  loop: "{{ cis_filesystem_modules }}"



#################################################
# Detect failures
#################################################


- name: Fail if module is loaded

  set_fact:

    cis_failed_modules: "{{ cis_failed_modules + [item.item] }}"

  when:

    - item.stdout != ""

  loop: "{{ module_loaded.results }}"



- name: Fail if blacklist missing

  set_fact:

    cis_failed_modules: "{{ cis_failed_modules + [item.item] }}"

  when:

    - "'blacklist ' + item.item not in item.stdout"

  loop: "{{ module_config.results }}"



- name: Fail if install false missing

  set_fact:

    cis_failed_modules: "{{ cis_failed_modules + [item.item] }}"

  when:

    - "'install ' + item.item + ' /bin/false' not in item.stdout"

  loop: "{{ module_config.results }}"



- name: Remove duplicate failed modules

  set_fact:

    cis_failed_modules: "{{ cis_failed_modules | unique }}"



- name: CIS Audit Report

  debug:

    msg:

      - "Filesystem modules requiring remediation:"
      - "{{ cis_failed_modules }}"
