---

- name: Audit filesystem kernel modules
  shell: |
    echo "===== {{ item }} ====="

    echo "Loaded:"
    lsmod | grep -w {{ item }} || echo "Not Loaded"

    echo "Config:"
    modprobe --showconfig | grep -E "^(blacklist|install)" | grep -w {{ item }} || echo "No configuration"

  loop: "{{ cis_filesystem_modules }}"
  register: audit_result


- name: Display audit result
  debug:
    var: audit_result.results
