---

- name: CIS 1.1.1 Audit filesystem kernel modules
  include_tasks: audit.yml


- name: CIS 1.1.1 Remediation filesystem kernel modules
  include_tasks: remediate.yml
  when:
    - cis_failed_modules | length > 0


- name: CIS 1.1.1 Final verification
  include_tasks: verify.yml
