---

- name: Verify loaded modules after remediation

  shell: |

    lsmod | grep -w "{{ item }}"

  register: verify_loaded

  failed_when: false

  changed_when: false

  loop: "{{ cis_filesystem_modules }}"



- name: Verify CIS module configuration

  shell: |

    modprobe --showconfig | grep -E "^(install|blacklist).*{{ item }}"

  register: verify_config

  failed_when: false

  changed_when: false

  loop: "{{ cis_filesystem_modules }}"



- name: CIS Final Compliance Report

  debug:

    msg:

      Module: "{{ item.item }}"

      Loaded:

        "{{ 'FAIL' if item.stdout != '' else 'PASS' }}"

  loop: "{{ verify_loaded.results }}"



- name: CIS Compliance Check

  assert:

    that:

      - verify_loaded.results | selectattr('stdout','ne','') | list | length == 0

    success_msg:

      "CIS 1.1.1 Filesystem Kernel Modules PASS"

    fail_msg:

      "CIS 1.1.1 Filesystem Kernel Modules FAILED"
