---

############################################
# Verify module is not loaded
############################################

- name: Verify kernel modules are not loaded
  shell: |
    lsmod | grep -w "{{ item }}"
  register: module_loaded
  failed_when: module_loaded.rc == 0
  changed_when: false
  loop: "{{ cis_filesystem_modules }}"


############################################
# Verify blacklist exists
############################################

- name: Verify blacklist configuration
  shell: |
    modprobe --showconfig | grep -P "^blacklist {{ item }}$"
  register: blacklist_check
  changed_when: false
  loop: "{{ cis_filesystem_modules }}"


############################################
# Verify install false exists
############################################

- name: Verify install false configuration
  shell: |
    modprobe --showconfig | grep -P "^install {{ item }} /bin/false$"
  register: install_check
  changed_when: false
  loop: "{{ cis_filesystem_modules }}"


############################################
# CIS Final Result
############################################

- name: CIS Compliance Result
  debug:
    msg:
      - "CIS 1.1.1 Filesystem Kernel Modules PASS"
      - "Modules disabled:"
      - "{{ cis_filesystem_modules }}"
