---

- name: Audit filesystem kernel modules
  include_tasks: audit.yml


- name: Remediate filesystem kernel modules
  include_tasks: remediate.yml
  when: cis_failed_modules | length > 0


- name: Verify filesystem kernel modules
  include_tasks: verify.yml